Repository datavorous/amine, pull requests merged in 2024-10, with the labels that each got.

#9 Support exe path
  amine/templates/index.html
  amine/webapp.py
Labels: hacktoberfest-accepted

#7 Issue #3 : Enhancements With Distraction Tracking, Data Storing And Visualization And CSV Export
  .gitignore
  LICENSE
  README.md
  amine/templates/data.html
  amine/templates/help.html
  amine/templates/index.html
  amine/webapp.py
  poetry.lock
  pyproject.toml
Labels: enhancement, hacktoberfest, assigned, hacktoberfest-accepted

#12 Add Toast Notifications for Invalid File Path and URLs using Plyer
  amine/webapp.py
  poetry.lock
  pyproject.toml
Labels: hacktoberfest, assigned, hacktoberfest-accepted
